example/urls.py
from django.urls import path
from example.views import user_list, log_in, log_out, sign_up, create_room, user_list1, chat_view


urlpatterns = [
    path('chat/<str:pk>/', chat_view, name='chat'),
    path('user1/', user_list1, name='user1'),
    path("room/", create_room, name='room'),
    path('', user_list, name='user_list'),
    path('log_in/', log_in, name='log_in'),
    path('log_out/', log_out, name='log_out'),
    path('sign_up/', sign_up, name='sign_up'),
    path('user1/log_out/', log_out, name='log_out')
]

app_name = 'example'

example_channels/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example.urls', namespace='example')),
]

example/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class LoggedInUser(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, related_name='logged_in_user', on_delete=models.CASCADE)



class Room(models.Model):
    label = models.CharField(max_length=50)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Message(models.Model):
    room = models.ForeignKey(Room ,related_name='messages', on_delete=models.CASCADE)
    message = models.TextField()

    def __str__(self):
        return self.message
    

example/forms.py
from django.forms import ModelForm
from .models import Room



class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'

example/views.py
from django.contrib.auth import login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.urls import reverse
from django.shortcuts import render, redirect
from .forms import RoomForm
from .models import Room, Message

# Create your views here.

User = get_user_model()


def user_list1(request):
    users = User.objects.select_related('logged_in_user')
    for user in users:
    
        user.status = 'Online' if hasattr(user, 'logged_in_user') else 'Offline'
    return render(request, 'example/user_list1.html', {'users': users})


def create_room(request):
    form = RoomForm()
    if request.method == 'POST':
        form = RoomForm(request.POST)
        if form.is_valid():
            form.save()
    context = {'form':form}
    return render(request, 'example/create_room.html', context)

@login_required(login_url='/log_in/')
def user_list(request):
    users = User.objects.select_related('logged_in_user')
    for user in users:
    
        user.status = 'Online' if hasattr(user, 'logged_in_user') else 'Offline'
    return render(request, 'example/user_list.html', {'users': users})



def log_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect(reverse('example:user_list'))
        else:
            print(form.errors)
    return render(request, 'example/log_in.html', {'form': form})



def log_out(request):
    logout(request)
    return redirect(reverse('example:log_in'))


def sign_up(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('example:log_in'))
        else:
            print(form.errors)
    return render(request, 'example/sign_up.html', {'form': form})


@login_required(login_url='/log_in/')
def chat_view(request, pk):
    room = Room.objects.get(label=pk)
    messages = Message.objects.filter(room=room)
    context = {'messages': messages}
    return render(request, 'example/chat_room.html', context)

example/templates/example/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <title>Example Channels</title>
</head>
<body>
  <div class="container">
    <br>
    {% block content %}{% endblock content %}
  </div>
  <script src="//code.jquery.com/jquery-3.1.1.min.js"></script>
  {% block script %}{% endblock script %}
</body>
</html>

example/templates/example/chat_room.html
{% extends 'example/base.html' %}

{% block content %}
<ul class="list-group">

</ul>
    {% for message in messages %}
        {{message}}<br>
    {% endfor %}
<!-- 
<form id="chat">
    <input id="message" type="text" value="this is"><br>
    <button type="submit">Submit</button>
</form> -->
<input id="chat-message-input" type="text" size="100"/><br/>
<input id="chat-message-submit" type="button" value="Send"/>

    
{% endblock %}
{% block script %}
<script>
    var socket = new WebSocket('ws://' + window.location.host + window.location.pathname);
    socket.onopen = function open(){
        console.log('WebSockets connection created for chatting ...');
       
    }

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        socket.send(message);

        messageInputDom.value = '';
    };
  
    socket.onmessage = function message(event) {
       var data = JSON.parse(event.data);
       console.log(data["messages"]);
       console.log(data["username"]);
       var ul = document.querySelector(".list-group");
       var li = document.createElement("li");
       var li2 = document.createElement("li");


       var message = document.createTextNode(data["messages"]);
       var user = document.createTextNode(data["username"]);
       li.appendChild(message);
       li2.appendChild(user);
       ul.appendChild(li);
       ul.appendChild(li2);

          };
  
    if (socket.readyState == WebSocket.OPEN) {
    socket.onopen();
    }

</script>
{% endblock %}

example/templates/example/create_room.html
{% extends 'example/base.html' %}
{% block content %}

<form action="" method="POST">{% csrf_token %}
    

    {{form.name.label}}
    {{form.name}}
    <input type="submit">
</form>
{% endblock %}

example/templates/example/log_in.html
{% extends 'example/base.html' %}

{% block content %}
  <form action="{% url 'example:log_in' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
      <div>
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    <button type="submit">Log in</button>
  </form>
  <p>Don't have an account? <a href="{% url 'example:sign_up' %}">Sign up!</a></p>
{% endblock content %}

example/templates/example/sign_up.html
{% extends 'example/base.html' %}

{% block content %}
  <form action="{% url 'example:sign_up' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
      <div>
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    <button type="submit">Sign up</button>
    <p>Already have an account? <a href="{% url 'example:log_in' %}">Log in!</a></p>
  </form>
{% endblock content %}

example/templates/example/user_list.html
{% extends 'example/base.html' %}

{% block content %}
  <a href="{% url 'example:log_out' %}">Log out</a>
  <br>
  <ul>
    {% for user in users %}
      <!-- NOTE: We escape HTML to prevent XSS attacks. -->
      <li data-username="{{ user.username|escape }}">
        {{ user.username|escape }}: {{ user.status|default:'Offline' }}
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

{% block script %}
  <script>
    var socket = new WebSocket('ws://' + window.location.host + '/users/'+'hello');

    socket.onopen = function open() {
      console.log('WebSockets connection created.');
      console.log(window.location.pathname)
    };

    socket.onmessage = function message(event) {
      var data = JSON.parse(event.data);
      // NOTE: We escape JavaScript to prevent XSS attacks.
      var username = encodeURI(data['username']);
      var user = $('li').filter(function () {
        return $(this).data('username') == username;
      });

      if (data['is_logged_in']) {
        user.html(username + ': Online');
      }
      else {
        user.html(username + ': Offline');
      }
    };

    if (socket.readyState == WebSocket.OPEN) {
      socket.onopen();
    }
  </script>
{% endblock script %}

example/templates/example/user_list1.html
{% extends 'example/base.html' %}


{% block content %}
  <a href="{% url 'example:log_out' %}">Log out</a>
  <br>
  <ul>
    {% for user in users %}
      <!-- NOTE: We escape HTML to prevent XSS attacks. -->
      <li data-username="{{ user.username|escape }}">
        {{ user.username|escape }}: {{ user.status|default:'Offline' }}
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

{% block script %}
  <script>
    var socket = new WebSocket('ws://' + window.location.host + '/users/');

    socket.onopen = function open() {
      console.log('WebSockets connection created.');
    };

    socket.onmessage = function message(event) {
      var data = JSON.parse(event.data);
      // NOTE: We escape JavaScript to prevent XSS attacks.
      var username = encodeURI(data['username']);
      var user = $('li').filter(function () {
        return $(this).data('username') == username;
      });

      if (data['is_logged_in']) {
        user.html(username + ': Online');
      }
      else {
        user.html(username + ': Offline');
      }
    };

    if (socket.readyState == WebSocket.OPEN) {
      socket.onopen();
    }
  </script>
{% endblock script %}